 <?php get_header(); ?>
 <?php require_once('includes/header-top.php'); ?>
 <?php require_once('includes/select.php'); ?>
 <?php require_once('includes/our.php'); ?>
 <?php require_once('includes/we.php'); ?>
 <?php require_once('includes/other.php'); ?>
 <?php require_once('includes/balkon.php'); ?>
 <?php require_once('includes/zamer.php'); ?>
 <?php require_once('includes/kachestvo.php'); ?> 
 <?php get_footer(); ?> 