 <?php get_header(); ?>
 <?php require_once('select.php'); ?>
 <?php require_once('our.php'); ?>
 <?php require_once('we.php'); ?>
 <?php require_once('other.php'); ?>
 <?php require_once('balkon.php'); ?>
 <?php require_once('zamer.php'); ?>
 <?php require_once('kachestvo.php'); ?>
 <?php get_footer(); ?>